from __future__ import annotations

import logging
from typing import Optional

import httpx
from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session

from apps.api.database import get_db
from apps.api.models import EntityRelationship, Entity, Mention, Document
from apps.api.services.graph_insights import build_nx_graph, top_broker_paths, graph_communities

log = logging.getLogger(__name__)
router = APIRouter(tags=["graph_insights"])


def _build_entity_map(db: Session, entity_ids: set | None = None) -> dict:
    q = db.query(Entity)
    if entity_ids:
        q = q.filter(Entity.id.in_(list(entity_ids)))
    return {str(e.id): e for e in q.all()}


def _source_entity_ids(db: Session, source_tag: str | None) -> set | None:
    if not source_tag:
        return None
    rows = (
        db.query(Mention.entity_id)
        .join(Document, Document.id == Mention.document_id)
        .filter(Document.source_tag == source_tag)
        .distinct()
        .all()
    )
    return {r[0] for r in rows}


def _filter_rels(rels, entity_ids: set | None):
    if entity_ids is None:
        return rels
    return [r for r in rels if r.entity_a_id in entity_ids and r.entity_b_id in entity_ids]


@router.get("/graph/broker-paths/{entity_id}")
def graph_broker_paths(
    entity_id: str,
    limit: int = Query(8, ge=1, le=25),
    source_tag: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """
    Return shortest paths through entity_id that bridge different parts of the graph.
    All nodes in the path are named.
    """
    rels = db.query(EntityRelationship).filter(EntityRelationship.weight >= 1).all()
    rels = _filter_rels(rels, _source_entity_ids(db, source_tag))

    G = build_nx_graph(rels)
    raw = top_broker_paths(G, entity_id, limit=limit)

    emap = _build_entity_map(db)

    # Resolve broker entity name
    broker = emap.get(entity_id)
    broker_name = broker.canonical_name if broker else entity_id
    broker_type = broker.entity_type if broker else "unknown"

    paths_out = []
    for item in raw:
        paths_out.append({
            "length": item["length"],
            "bridge_position": item["bridge_position"],
            "bridge_score": item["bridge_score"],
            "nodes": [
                {
                    "id": nid,
                    "name": emap[nid].canonical_name if nid in emap else nid,
                    "entity_type": emap[nid].entity_type if nid in emap else "unknown",
                    "mention_count": emap[nid].mention_count if nid in emap else 0,
                }
                for nid in item["path"]
            ],
        })

    return {
        "broker_id": entity_id,
        "broker_name": broker_name,
        "broker_type": broker_type,
        "path_count": len(paths_out),
        "paths": paths_out,
    }


@router.get("/graph/communities")
def get_graph_communities(
    source_tag: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """
    Detect graph communities (Louvain/greedy modularity).
    Returns named members, density, and key actor per community.
    """
    rels = db.query(EntityRelationship).filter(EntityRelationship.weight >= 1).all()
    rels = _filter_rels(rels, _source_entity_ids(db, source_tag))

    G = build_nx_graph(rels)
    emap = _build_entity_map(db)

    return graph_communities(G, entity_map=emap)


@router.get("/graph/communities/summary")
def get_community_summaries(
    source_tag: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """
    Per-community narrative summary generated by local LLM (Ollama).
    Returns: [{community_id, key_actor, member_names, summary}]
    Falls back to template summary if Ollama unavailable.
    """
    rels = db.query(EntityRelationship).filter(EntityRelationship.weight >= 1).all()
    rels = _filter_rels(rels, _source_entity_ids(db, source_tag))

    G = build_nx_graph(rels)
    emap = _build_entity_map(db)
    communities_data = graph_communities(G, entity_map=emap)

    results = []
    for comm in communities_data["communities"]:
        member_names = [m["name"] for m in comm["members"] if m.get("entity_type") != "Location"]
        org_names    = [m["name"] for m in comm["members"] if m.get("entity_type") == "Organization"]
        person_names = [m["name"] for m in comm["members"] if m.get("entity_type") == "Person"]

        summary_text = _generate_community_summary(
            community_id=comm["community_id"],
            key_actor=comm["key_actor"],
            org_names=org_names,
            person_names=person_names,
            density=comm["density"],
        )

        results.append({
            "community_id": comm["community_id"],
            "size": comm["size"],
            "density": comm["density"],
            "key_actor": comm["key_actor"],
            "organizations": org_names,
            "persons": person_names,
            "summary": summary_text,
        })

    return {
        "community_count": len(results),
        "communities": results,
    }


def _generate_community_summary(
    community_id: int,
    key_actor: str,
    org_names: list[str],
    person_names: list[str],
    density: float,
) -> str:
    """
    Call Ollama phi3 to generate a one-sentence investigative summary of a community cluster.
    Falls back to a template string if Ollama is unavailable.
    """
    orgs_str    = ", ".join(org_names) if org_names else "no organizations"
    persons_str = ", ".join(person_names) if person_names else "no identified individuals"

    prompt = (
        f"You are an investigative analyst. Based on the following co-occurrence cluster from legal documents, "
        f"write a single concise sentence (max 30 words) describing what this cluster likely represents.\n\n"
        f"Key actor: {key_actor}\n"
        f"Organizations: {orgs_str}\n"
        f"Individuals: {persons_str}\n"
        f"Cluster density: {density} (0=sparse, 1=fully connected)\n\n"
        f"Respond with only the summary sentence, no preamble."
    )

    try:
        resp = httpx.post(
            "http://localhost:11434/api/generate",
            json={"model": "phi3:latest", "prompt": prompt, "stream": False},
            timeout=30.0,
        )
        if resp.status_code == 200:
            text = resp.json().get("response", "").strip()
            if text:
                return text
    except Exception as e:
        log.warning("Ollama unavailable for community summary: %s", e)

    # Template fallback
    if org_names and person_names:
        return f"Cluster centered on {key_actor}, involving {len(org_names)} organizations and {len(person_names)} individuals."
    elif org_names:
        return f"Organizational cluster centered on {key_actor} with {len(org_names)} connected entities."
    else:
        return f"Cluster of {len(person_names)} individuals connected through {key_actor}."


@router.get("/graph/brokers")
def get_top_brokers(
    top_n: int = Query(10, ge=1, le=50),
    source_tag: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """
    Return top N structural brokers — entities that bridge multiple communities.
    Uses betweenness centrality as the primary signal.
    """
    import networkx as nx

    rels = db.query(EntityRelationship).filter(EntityRelationship.weight >= 1).all()
    rels = _filter_rels(rels, _source_entity_ids(db, source_tag))

    G = build_nx_graph(rels)
    if G.number_of_nodes() == 0:
        return {"brokers": []}

    emap = _build_entity_map(db)
    communities_data = graph_communities(G, entity_map=emap)
    membership = communities_data["membership"]

    bc = nx.betweenness_centrality(G, weight="weight", normalized=True)
    deg = nx.degree_centrality(G)

    brokers = []
    for nid, bc_score in sorted(bc.items(), key=lambda x: x[1], reverse=True)[:top_n]:
        e = emap.get(nid)
        if not e:
            continue

        # Count how many distinct communities this entity's neighbors are in
        neighbor_communities = {
            membership.get(str(nbr))
            for nbr in G.neighbors(nid)
            if membership.get(str(nbr)) is not None
        }
        own_community = membership.get(str(nid))
        bridged = len(neighbor_communities - {own_community})

        brokers.append({
            "id": nid,
            "name": e.canonical_name,
            "entity_type": e.entity_type,
            "mention_count": e.mention_count,
            "betweenness": round(bc_score, 4),
            "degree": round(deg.get(nid, 0), 4),
            "own_community": own_community,
            "communities_bridged": bridged,
            "connections": G.degree(nid),
        })

    return {
        "broker_count": len(brokers),
        "brokers": brokers,
    }
